# Generated by Django 4.0.2 on 2022-02-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(default='', max_length=25),
        ),
    ]
